### ISSUE TITLE
more style to the home page

### ISSUE THREAD

**Issue by chavi362** [chavi362/Icy-Tower#25]
Currentlt the style of the homepage isn't so nice please improve this

**Comment by prakharbhardwaj1504** [comment]
Hey, assign this to me .I will do it ASAP.

**Comment by Payne680** [comment]
Please assign this to me ?

**Comment by chavi362** [comment]
@Payne680 , I'm so sorry but @prakharbhardwaj1504 asked me before.
If you want, there are more issues you can pick up.
Please you both @Payne680 and @prakharbhardwaj1504 give the project a star and share it with your friends.
Thanks
Chavi362

**Comment by chavi362** [comment]
@prakharbhardwaj1504 how are you with the work?

**Comment by prakharbhardwaj1504** [comment]
need some time
