### ISSUE TITLE
Config Prettier

### ISSUE THREAD

**Issue by N3v1** [chavi362/Icy-Tower#6]
Hi @chavi362, 
I can config prettier a code formatter which I also use in many repos of mine
Pls assign this issue to me

**Comment by N3v1** [comment]
Hi @chavi362, I'll work on it now. 

If you have time, we could need some help in [**this repo**](https://github.com/TeamCodeArena/DeliverEase) and [**that repo**](https://github.com/TeamCodeArena/deliverease.app).

**Comment by chavi362** [comment]
merged PR
