### ISSUE TITLE
UI Revamp

### ISSUE THREAD

**Issue by N3v1** [chavi362/Icy-Tower#8]
Hi @chavi362,
I have some ideas for a new well-designed GUI:

- [ ] Maybe use another font
- [ ]

**Comment by N3v1** [comment]
Hi @chavi362, could you please deploy your code to GitHub pages so that I can find more issues which I can contribute to

**Comment by chavi362** [comment]
What are you meaning deploying the code?

**Comment by chavi362** [comment]
I owe you a big thank you for your involvement in my project!!
Thank you so much!!!

**Comment by chavi362** [comment]
Did you try to play the game? I'll would be happy to read your feedback.
Thank you so much!!!

**Comment by N3v1** [comment]
No, I didn‘t but I try to play it today @chavi362

**Comment by chavi362** [comment]
Hi @N3v1 how are you?
Longtime passed since we chatted....
Do you still work on it?
Do you want some help?
I add 2 another open sources virtual-keyboard and get to 100! i would like to see you there!
